# Creating a dictionary of the 50 most searched things on Google
most_searched_google = {
    'Weather': 1,
    'News': 2,
    'Google': 3,
    'Facebook': 4,
    'YouTube': 5,
    'Amazon': 6,
    'Netflix': 7,
    'Translate': 8,
    'WhatsApp': 9,
    'Instagram': 10,
    'COVID-19': 11,
    'Jobs': 12,
    'Games': 13,
    'Sports': 14,
    'Music': 15,
    'Movies': 16,
    'Recipes': 17,
    'Travel': 18,
    'Health': 19,
    'Technology': 20,
    'Fashion': 21,
    'Finance': 22,
    'Education': 23,
    'Shopping': 24,
    'Fitness': 25,
    'Science': 26,
    'Space': 27,
    'Art': 28,
    'Politics': 29,
    'Food': 30,
    'History': 31,
    'Animals': 32,
    'Books': 33,
    'Gardening': 34,
    'Photography': 35,
    'DIY': 36,
    'Home Decor': 37,
    'Cars': 38,
    'Technology News': 39,
    'Memes': 40,
    'Celebrities': 41,
    'Hobbies': 42,
    'Weather Forecast': 43,
    'Travel Destinations': 44,
    'Mobile Apps': 45,
    'How-to Guides': 46,
    'Podcasts': 47,
    'Virtual Reality': 48,
    'Pet Care': 49,
    'Self-improvement': 50
}



#THE TEXT TO START THE GAME
start_text = "press space to start the game"

